'use client';

import { motion } from 'framer-motion';
import { Quote, Star } from 'lucide-react';

const REVIEWS = [
  {
    name: "Asif Rahman",
    role: "Verified Buyer",
    text: "The fabric quality is simply outstanding! The 240 GSM oversized t-shirt feels truly premium. No fading or shrinkage even after washing."
  },
  {
    name: "Tanvir Ahmed",
    role: "Verified Buyer",
    text: "The minimalist Pima tee fits perfectly. It feels incredibly premium on the skin. Will definitely order more colors soon!"
  },
  {
    name: "Sajid Islam",
    role: "Verified Buyer",
    text: "The fit of the polo shirts is amazing. The collar grip stays perfectly in place. Best choice for casual office wear or outdoors."
  }
];
export default function Testimonials() {
  return (
    <section className="py-16 bg-white dark:bg-[#0F1322]/40">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        <div className="text-center max-w-xl mx-auto">
          <h2 className="text-3xl font-black text-gray-900 dark:text-white tracking-tight">What Our Tribe Says</h2>
          <p className="text-xs text-gray-500 mt-2">Real feedback generated by our structural clothing community nodes.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {REVIEWS.map((rev, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, scale: 0.95 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: idx * 0.1 }}
              className="p-6 bg-[#F9FAFB] dark:bg-gray-950 border border-gray-100 dark:border-gray-900 rounded-2xl relative space-y-4 shadow-sm"
            >
              <Quote className="absolute right-6 top-6 text-gray-200 dark:text-gray-900 w-8 h-8 pointer-events-none" />
              <div className="flex gap-0.5 text-amber-500">
                {[...Array(5)].map((_, i) => <Star key={i} size={14} className="fill-amber-500" />)}
              </div>
              <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed font-medium italic">"{rev.text}"</p>
              <div className="pt-2 border-t border-gray-100 dark:border-gray-900">
                <h4 className="text-xs font-bold text-gray-900 dark:text-white">{rev.name}</h4>
                <p className="text-[10px] text-gray-400">{rev.role}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}